name: build-android-demo-package

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore workloads
      run: dotnet workload restore
    - name: Build control
      run: |
        mkdir -p local_package
        ./build.sh
    - name: Setup Android SDK Tools
      uses: android-actions/setup-android@v2.0.2
    - name: Publish package
      run: dotnet publish ./sample.Android/AvaloniaGraphControlSample.Android.csproj -p:UseControlOnNuget=True -c Release -p:PublishTrimmed=true
    - name: Android Sign
      uses: Tlaster/android-sign@v1.2.2
      with:
        releaseDirectory: sample.Android/bin/Release/net7.0-android/publish/
        signingKeyBase64: ${{secrets.KEYSTORE}}
        alias: ${{secrets.SIGNINGKEY_ALIAS}}
        keyStorePassword: ${{secrets.KEYSTORE_PASSWORD}}
        keyPassword: ${{secrets.SIGNINGKEY_PASSWORD}}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: android-signed
        path: build/signed
        retention-days: 0

