name: build-ios-demo-package

on:
  workflow_dispatch:
  push:
    branches: [ "ios" ]

jobs:

  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore workloads
      run: dotnet workload restore
    - name: Build control
      run: |
        mkdir -p local_package
        ./build.sh
    - name: Publish package
      run: dotnet publish ./sample.iOS/AvaloniaGraphControlSample.iOS.csproj -r ios-arm64 -p:UseControlOnNuget=True -c Release -p:PublishTrimmed=true
    - name: Upload unsigned package as artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: ios-unsigned
        path: sample.iOS/bin/Release/net7.0-ios/publish
        retention-days: 0


