name: publish-to-wasm-demo

on:
  push:
    branches: [ "ga_setup" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore workloads
      run: dotnet workload restore
    - name: Build control
      run: |
        mkdir -p local_package
        ./build.sh
    - name: Build sample
      run: dotnet build ./sample.Browser/AvaloniaGraphControlSample.Browser.csproj -c Debug /p:UseControlOnNuget=True
    - name: Fix permissions
      run: |
        chmod -c -R +rX "sample.Browser/bin/Debug/net7.0/browser-wasm/AppBundle/" | while read line; do
          echo "::warning title=Invalid file permissions automatically fixed::$line"
        done
    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v2.0.0
      with:
        path: sample.Browser/bin/Debug/net7.0/browser-wasm/AppBundle/

  deploy:
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy GitHub Pages site
      id: deployment
      uses: actions/deploy-pages@v1.2.9

